services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    container_name: vite-project-frontend
    environment:
      - NODE_ENV=production
    restart: unless-stopped
